### ISSUE TITLE
Add caching to Github Action workflows

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-website#59]
It would be good to have caching to enable

1. complete website previews for Pull Requests

**Comment by mmcky** [comment]
https://github.com/actions/cache

**Comment by mmcky** [comment]
The GitHub implementation of `cache` works but isn't up-dateable. 

So it would give the "feel" of a complete site but the PR will build the changed RST files and overwrite those lectures in the `_build/website/jupyter_html` folder. 

I have written to GitHub to see if there is a way to save/retrieve artifacts to a central location to get updated copies of the site as PR's roll through.

**Comment by mmcky** [comment]
- [ ] We could have a `daily` cache with the date parameter added to the `cache` key if this becomes an issue. 

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
```
